#!/bin/bash
#
# test exit output with a bigger number than the limit one

command="exit 259"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# run command
echo "$command" | $SHELL
echo $? > salida

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat salida | grep 3| wc -l`
if [ $nmatch -eq 1 ]; then
       print_ok
else
       print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
rm salida
